### ISSUE TITLE
App not running

### ISSUE THREAD

**Issue by objque** [airk000/Trigger#1]
Hello, 
I write this simple code:

![default](https://cloud.githubusercontent.com/assets/7000585/8267740/651ee6c8-1774-11e5-91be-debd36c5c625.PNG)
(breakpoint not called)

And app not running. If i remove this code, everything works.
I add service into manifest :(
Whats I`am doing wrong? 

Device with - Android L

**Comment by lkv1988** [comment]
It doesn't make sense, the library not throw an exception?  OK, there it is. You need give the job an condition at least. As we know, A job only can be triggered while its condition(s) are all satisfied, so a job without any conditions is illegal. 

You can just make your own condition or just use the three internal condition, they are all broardcast in fact. Please see the README again, you can't miss it.
