### ISSUE TITLE
time condition

### ISSUE THREAD

**Issue by rotman** [airk000/Trigger#2]
Hi,
how can i use trigger for pre-defined time, once a day?
thanks :)

**Comment by lkv1988** [comment]
You mean you don't want define the exact time but only want something be triggered once in a day, am i right?

**Comment by rotman** [comment]
I want that something will happen in exact time, onca a day.

**Comment by lkv1988** [comment]
OK, I got it. So I think u don't need trigger at all, AlarmManager can do it well.

Set a alarm via AlarmManager for sending a custom broadcast, and then register a receiver for this broadcast, while you receive the broadcast, do the thing. Just set the interval time to 24h then you will got it once a day. How about this?

**Comment by rotman** [comment]
I wanted to avoid using AlarmManager...
Never mind, thank you :)
