### ISSUE TITLE
Is Example wokring fine?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [airk000/Trigger#3]
I copied the code from the example:

```
Job persistAfterRebootJob = new Job(true, new PersistAfterRebootWithChargingAction())
                .attachOn(ThreadSpace.MAIN)
                .repeat(71 * 60 * 1000)
                .needCharging(true);
        trigger.schedule(job1, job2, job3, persistAfterRebootJob);
```

Since you have not supplied any condition i assume that it does not require. 

But i am getting the exception:

`java.lang.IllegalArgumentException: Please check your Job, it can not be triggered at all without any conditions.`

Please correct the example or me :)

**Comment by lkv1988** [comment]
Sorry, my fault. Any job must has at least one condition, I'll edit it in the right way. Thanks for report.
