### ISSUE TITLE
Persistable repeated job is executed twice

### ISSUE THREAD

**Issue by yolapop** [airk000/Trigger#4]
Hi there, I just found out this awesome library.... great job, it just takes 15 minutes to implement...

however, please check your sample...

``` java

    public static class PersistAfterRebootWithChargingAction extends ContextAction {

        @Override
        protected void act(Context context) {
            Log.v("mylog", "act " + System.currentTimeMillis());
            Toast.makeText(context, "Charging...(from persist Job after reboot)", Toast.LENGTH_SHORT).show();
        }
    }

```

I put a log there and it's executed twice if `repeat()` is used

**Comment by lkv1988** [comment]
Thanks for feedback this issue, it's a bug and I'm on it.

There is really two jobs have been triggered, they are same in fact. But the first one from persist-able job recovery, and the last one from developer scheduled, they are not the same object.

I've try to find out a better way to handle this sense.

**Comment by lkv1988** [comment]
I have release the 1.1.0, this issue has been fixed.

Please try it. :)
