### ISSUE TITLE
Error:Could not find trigger.jar

### ISSUE THREAD

**Issue by hasancse91** [airk000/Trigger#6]
I tried to use your library using gradle. But Gradle sync failed. The error message is given below:

`Error:Could not find trigger.jar (com.github.airk000:trigger:1.1.0).
Searched in the following locations:
    https://jcenter.bintray.com/com/github/airk000/trigger/1.1.0/trigger-1.1.0.jar`

What should I do?

**Comment by mariocaseres** [comment]
Try to use the compile 'com.github.airk000:trigger:1.0.0' version.

**Comment by lkv1988** [comment]
Sorry for that, im working on it, just upload a new version and tobe checked, while i have some news, i'll tell let u know ASAP.

**Comment by lkv1988** [comment]
@hasancse91 finally solve it. Plz use mavenCentral() and update version to 1.1.1
